import Head from "next/head";
import Avatar from "../components/Avatar";
import { MicrophoneIcon, ViewGridIcon } from "@heroicons/react/solid";
import { SearchIcon, PlusIcon } from "@heroicons/react/outline";
import Image from "next/image";
import Footer from "../components/Footer";
import { useRef } from "react";
import { useRouter } from "next/router";
export default function Home() {
  const router = useRouter();

  const searchInputRef = useRef(null);

  const search = (e) => {
    e.preventDefault();
    const term = searchInputRef.current.value;

    if (!term) return;

    // React Router function is going on
    router.push(`/search?term=${term}`);
  };
  return (
    <div className=" flex flex-col items-center justify-center h-screen">
      <Head>
        <title>Google</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/**header */}
      <header className="flex p-7 w-full text-sm text-gray-700  justify-between">
        {/**left */}
        <div className="flex space-x-4 items-center">
          <p className="link">About</p>
          <p className="link">Store</p>
        </div>
        {/**right */}
        <div className="flex space-x-4 items-center">
          <p className="link">Gmail</p>
          <p className="link">Images</p>

          <ViewGridIcon className="h-10 w-10 p-2 rounded-full hover:bg-gray-100 cursor-pointer" />
          <Avatar
            url={"https://hindibate.com/wp/WhatsApp-DP-For-Girls-HD-1686.png"}
          />
        </div>
      </header>

      {/**body */}
      <form className=" flex flex-col items-center mt-10 lg:mt-40 flex-grow w-4/5">
        <Image
          src="https://www.google.co.uk/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png"
          className="cursor-pointer sm:h-10"
          height={80}
          width={240}
        />
        <div className="flex w-full mt-5 hover:shadow-lg focus-within:shadow-lg max-w-md px-5 py-3 rounded-full border border-gray-100 items-center sm:max-w-xl lg:max-w-2xl">
          <button onClick={search}>
            <SearchIcon className="h-5 text-gray-500 mr-3 cursor-pointer" />
          </button>
          <input
            ref={searchInputRef}
            type="text"
            className=" flex-grow focus:outline-none"
            placeholder="Search Google or type a URL"
          />
          <MicrophoneIcon className=" text-gray-500 h-5 cursor-pointer" />
        </div>
        <div className="flex justify-center mt-7">
          <button
            onClick={search}
            className="mx-3 bg-gray-100 px-2 py-2 hover:bg-gray-200 cursor-pointer link rounded-md"
          >
            Google Search
          </button>
          <button
            onClick={search}
            className="mx-3  bg-gray-100 px-2 py-2 hover:bg-gray-200 cursor-pointer link rounded-md"
          >
            I'm Feeling lucky
          </button>
        </div>
        <div className=" flex justify-center">
          <div className=" py-3 px-2 rounded-md flex flex-col items-center mt-7 hover:bg-gray-100 ">
            <PlusIcon className=" text-white bg-gray-600 h-11 p-3 rounded-full transition duration-150 transform hover:scale-110 cursor-pointer" />
            <p>Add shotcut</p>
          </div>
        </div>
      </form>

      {/**footer */}
      <Footer />
    </div>
  );
}
